CREATE TABLE IF NOT EXISTS `glpi_plugin_projecthelper_configurations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `replication_mode` VARCHAR(32) NOT NULL DEFAULT 'manual',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;